server:
  port: 8080
  servlet:
    contextPath:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kuback?createDatabaseIfNotExist=true
    username: admin
    password: 1234
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    open-in-view: false

  kafka:
    bootstrap-servers: "http://localhost:9092"

mailSender:
  username:
  password: